server:
  port: ${shop.port}
  servlet:
    context-path: /api
spring:
  redis:
    database: 0
    host: 47.100.185.39
    password: 211592
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
  datasource:
    url: jdbc:mysql://47.100.185.39:3306/redis_test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: cL211592.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect  #不加这句则默认为myisam引擎
    open-in-view: true

